version: 0.2
env:
  secrets-manager:  
    username: "arn:aws:secretsmanager:ap-south-1:853447314930:secret:prod/docker/login-T5vmpG:docker_id::"
    password: "arn:aws:secretsmanager:ap-south-1:853447314930:secret:prod/docker/login-T5vmpG:docker_password::"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "logging in to docker"
      - docker login --username $username --password $password
      - echo "logged in"
  build:
    commands:
      - mvn install
      - echo "building image"
      - docker build . -t sunddas/checking3
  post_build:
    commands:
      - echo "pushing image"
      - docker push sunddas/checking3